type FeatureInput = {
  id: string;
  label: string;
  capability: string;
  description: string;
  kind: "app-section" | "surface" | "data-model" | "game-system";
};

const feature = (spec: FeatureInput) => spec;

export const productFeatures = {
  mapFrame: feature({
    id: "map-frame",
    label: "Map Frame",
    capability: "map",
    kind: "surface",
    description: "GPS-first map shell that answers where am I, where have I been, and where should I go without exposing raw debug mechanics.",
  }),
  mapDebugControls: feature({
    id: "map-debug-controls",
    label: "Map Debug Controls",
    capability: "map",
    kind: "surface",
    description: "Developer-only on-screen controls for moving the gameplay marker and injecting map gestures so map state can be tested without real walking.",
  }),
  playerMarkerAccuracyRing: feature({
    id: "player-marker-accuracy-ring",
    label: "Player Marker + Accuracy Ring",
    capability: "map",
    kind: "surface",
    description: "Trusted gameplay position surface with marker smoothing, accuracy ring, and suspended-exploration ring state for unreliable GPS.",
  }),
  fogOverlay: feature({
    id: "fog-overlay",
    label: "Fog Overlay",
    capability: "map",
    kind: "surface",
    description: "Visual reveal layer for present, explored, frontier, unknown, and beyond states, tuned to make movement feel like cozy accumulation.",
  }),
  mapCellDetailSheet: feature({
    id: "map-cell-detail-sheet",
    label: "Map Cell Detail Sheet",
    capability: "map",
    kind: "surface",
    description: "Tap/detail sheet that describes the current Voronoi map cell before deeper discovery or collection systems take over.",
  }),
  nearbyOpportunityLayer: feature({
    id: "nearby-opportunity-layer",
    label: "Nearby Opportunity Layer",
    capability: "map",
    kind: "surface",
    description: "Reachable tease layer for nearby unexplored map cells and possible finds, so the map says where should I go next.",
  }),
  worldEventCueLayer: feature({
    id: "world-event-cue-layer",
    label: "World Event Cue Layer",
    capability: "map",
    kind: "surface",
    description: "Map cue layer for optional time-sensitive happenings such as Wildlife Migration without making events the core map loop.",
  }),
  districts: feature({
    id: "districts",
    label: "Districts",
    capability: "map",
    kind: "app-section",
    description: "Local territory view where explored map cells roll up into neighborhood/district progress, labels, and nearby completion.",
  }),
  cities: feature({
    id: "cities",
    label: "Cities",
    capability: "map",
    kind: "app-section",
    description: "City-scale atlas view where district progress combines into city identity, pride, and navigation.",
  }),
  states: feature({
    id: "states",
    label: "States",
    capability: "map",
    kind: "app-section",
    description: "State or province passport view where city progress becomes larger regional travel progress.",
  }),
  countries: feature({
    id: "countries",
    label: "Countries",
    capability: "map",
    kind: "app-section",
    description: "Country-scale passport view where state/province progress becomes national exploration progress.",
  }),
  world: feature({
    id: "world",
    label: "World",
    capability: "map",
    kind: "app-section",
    description: "World atlas view where the player's lifelong footprint becomes global progress.",
  }),
  territoryNavigation: feature({
    id: "territory-navigation",
    label: "Territory Navigation",
    capability: "map",
    kind: "surface",
    description: "Zoom ladder and navigation rules connecting GPS cell view to District, City, State, Country, and World views.",
  }),
  explorationEligibilityState: feature({
    id: "exploration-eligibility-state",
    label: "Exploration Eligibility State",
    capability: "map",
    kind: "data-model",
    description: "State model that decides when movement may record visits, reveal fog, and trigger discovery handoff versus when GPS trust pauses play.",
  }),
  cellEntryModel: feature({
    id: "cell-entry-model",
    label: "Map Cell Entry Model",
    capability: "map",
    kind: "data-model",
    description: "Map-cell entry model that turns eligible movement into a single reward-clean entry event, with Voronoi border crossing treated as a geometric implementation detail.",
  }),
  fogStateModel: feature({
    id: "fog-state-model",
    label: "Fog State Model",
    capability: "map",
    kind: "data-model",
    description: "Computed fog relationship model derived from current marker cell, visit history, and shared map-cell borders without persisted fog snapshots.",
  }),
  globalMapStateModel: feature({
    id: "global-map-state-model",
    label: "Global Map State Model",
    capability: "map",
    kind: "data-model",
    description: "Shared daily/weekly/season/permanent map state model where map cells refresh globally on GMT cadence while player visits, fog, and claims remain personal.",
  }),
  territoryProgressModel: feature({
    id: "territory-progress-model",
    label: "Territory Progress Model",
    capability: "map",
    kind: "data-model",
    description: "Rollup model for district, city, state, country, and world progress from explored map cells.",
  }),
  worldEventInstanceModel: feature({
    id: "world-event-instance-model",
    label: "World Event Instance Model",
    capability: "map",
    kind: "data-model",
    description: "Timed event instance model for map-visible happenings, locations, expiration, eligibility, and event detail handoff.",
  }),

  zoology: feature({
    id: "zoology",
    label: "Zoology",
    capability: "zoology",
    kind: "app-section",
    description: "Animal-focused discipline section surfaced through the Field Guide feature for fauna, threatened species meaning, behavior, signs, and migrations.",
  }),
  botany: feature({
    id: "botany",
    label: "Botany",
    capability: "botany",
    kind: "app-section",
    description: "Plant-focused discipline section surfaced through the Field Guide feature for flora, habitats, growth stages, and seasonal plant states.",
  }),
  mycology: feature({
    id: "mycology",
    label: "Mycology",
    capability: "mycology",
    kind: "app-section",
    description: "Fungi-focused discipline section surfaced through the Field Guide feature for fungal finds, substrates, spores, and hidden environmental conditions.",
  }),
  geology: feature({
    id: "geology",
    label: "Geology",
    capability: "geology",
    kind: "app-section",
    description: "Rock and mineral discipline section surfaced through the Field Guide feature for mineral finds, specimens, and landform context.",
  }),
  paleontology: feature({
    id: "paleontology",
    label: "Paleontology",
    capability: "paleontology",
    kind: "app-section",
    description: "Fossil discipline section surfaced through the Field Guide feature for extinct life, fossil records, and deep-time timeline context.",
  }),
  genetics: feature({
    id: "genetics",
    label: "Genetics",
    capability: "genetics",
    kind: "data-model",
    description: "Trait and inheritance model surfaced through the Field Guide feature for variation within species and generation-to-generation changes.",
  }),
  archaeology: feature({
    id: "archaeology",
    label: "Archaeology",
    capability: "archaeology",
    kind: "app-section",
    description: "Artifact and human-trace discipline section surfaced through the Field Guide feature for material culture, ruins, and place-based human history.",
  }),

  discovery: feature({
    id: "discovery",
    label: "Discovery",
    capability: "exploration-discovery-lifecycle",
    kind: "game-system",
    description: "Resolver and reward bridge from reward-clean map-cell entry into quiet revisits, committed unidentified living-specimen rewards, Slay the Spire-style reward modal presentation, queued reward continuation, and fly-to-Pack impact before Identification reveals known finds.",
  }),
  pack: feature({
    id: "pack",
    label: "Pack",
    capability: "exploration-discovery-lifecycle",
    kind: "app-section",
    description: "Owned unidentified and identified-find inventory that verifies Discovery acquisition with grid/search, filters, find cards, details, identification state, acquisition provenance, and reward-card landing impact feedback.",
  }),
  identification: feature({
    id: "identification",
    label: "Identification",
    capability: "exploration-discovery-lifecycle",
    kind: "surface",
    description: "Required unknown-to-known follow-up system for unidentified finds acquired from Discovery, revealing species identity, deterministic traits, and known Pack state.",
  }),

  town: feature({
    id: "town",
    label: "Town",
    capability: "living-world",
    kind: "app-section",
    description: "Top-level NPC-led world surface that lists unlocked local feature venues and opens each one bound to the nearest eligible local NPC.",
  }),
  npcVenues: feature({
    id: "npc-venues",
    label: "NPC Venues",
    capability: "living-world",
    kind: "data-model",
    description: "City-scoped, POI-anchored venue placement model for authored NPC functions: one NPC type per city, one NPC venue per cell, placed at the most popular eligible POI.",
  }),
  wildlifeRehabilitationCenter: feature({
    id: "wildlife-rehabilitation-center",
    label: "Wildlife Rehabilitation Center",
    capability: "living-world",
    kind: "surface",
    description: "First concrete NPC venue/role: a city-owned Wildlife Rehabilitation Center run by a Wildlife Rehabilitator that introduces Release to Wild.",
  }),

  fieldGuide: feature({
    id: "field-guide",
    label: "Field Guide",
    capability: "progression-permanence",
    kind: "app-section",
    description: "Persistent knowledge codex where species pages, discipline sections, learned observations, and known-find history outlive inventory ownership.",
  }),
  conservation: feature({
    id: "conservation",
    label: "Conservation",
    capability: "progression-permanence",
    kind: "game-system",
    description: "Stewardship layer for threat status meaning, conservation goals, and species/place care context.",
  }),
  releaseToWild: feature({
    id: "release-to-wild",
    label: "Release to Wild",
    capability: "progression-permanence",
    kind: "game-system",
    description: "Wildlife rehabilitation loop where players perform base one-off releases for a flat Orb item-stack reward, optionally contribute eligible fauna to local conservation programs for fixed bonus Orb item-stack rewards, remove released animals from active Pack, and preserve release history.",
  }),
  collections: feature({
    id: "collections",
    label: "Collections",
    capability: "progression-permanence",
    kind: "app-section",
    description: "Collection catalog, collection details, bundle slots, donation/commit flow, cross-domain sets, and completion rewards.",
  }),
  sanctuary: feature({
    id: "sanctuary",
    label: "Sanctuary",
    capability: "progression-permanence",
    kind: "app-section",
    description: "Persistent personal base/world with placement model, growth state, and placed-find details.",
  }),
  buddy: feature({
    id: "buddy",
    label: "Buddy",
    capability: "progression-permanence",
    kind: "app-section",
    description: "Active companion system with buddy slot, map presence, and tamagotchi-style care state/panel.",
  }),
  lineage: feature({
    id: "lineage",
    label: "Lineage",
    capability: "progression-permanence",
    kind: "game-system",
    description: "Family tree, breeding pairing flow, offspring result model, inherited traits, and lineage rarity chase.",
  }),

  quests: feature({
    id: "quests",
    label: "Quests",
    capability: "motivation",
    kind: "app-section",
    description: "Science quest board, quest details, progress model, and rewards for directed field goals.",
  }),
  achievements: feature({
    id: "achievements",
    label: "Achievements",
    capability: "motivation",
    kind: "app-section",
    description: "Achievement list, milestone unlocks, achievement diaries, and progress models for recognized mastery.",
  }),
  recap: feature({
    id: "recap",
    label: "Recap",
    capability: "motivation",
    kind: "surface",
    description: "Return recap card stack with progress deltas, world changes, and dismissal model.",
  }),

  community: feature({
    id: "community",
    label: "Community",
    capability: "multiplayer",
    kind: "app-section",
    description: "Community progress surfaces, aggregate discovery model, community events, and shared milestones.",
  }),
  economy: feature({
    id: "economy",
    label: "Economy",
    capability: "multiplayer",
    kind: "game-system",
    description: "Duplicate value, trading flow, market signal sections, and exchangeable surplus/resource value.",
  }),
} as const;
