#!/usr/bin/env python3
"""Generate EarthNova's current and approved target C4 architecture diagrams."""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / 'docs' / 'c4'
MMD_HEADER = '%% GENERATED by scripts/generate_c4_diagrams.py — do not edit.\n'
README_HEADER = '<!-- GENERATED by scripts/generate_c4_diagrams.py — do not edit. -->\n'
MERMAID_INIT = (
    "%%{init: {'theme': 'base', 'themeVariables': {"
    "'background': '#ffffff', 'primaryTextColor': '#0f172a', "
    "'lineColor': '#475569', 'fontFamily': 'Arial, sans-serif', "
    "'edgeLabelBackground': '#ffffff', 'actorLineColor': '#64748b', "
    "'signalColor': '#334155', 'labelBoxBorderColor': '#475569', "
    "'labelTextColor': '#0f172a', 'loopLineColor': '#64748b', "
    "'loopTextColor': '#0f172a'"
    "}, 'sequence': {'mirrorActors': false, 'diagramMarginX': 30, "
    "'diagramMarginY': 20, 'actorMargin': 40, 'messageMargin': 35}, "
    "'flowchart': {'curve': 'linear', 'nodeSpacing': 40, 'rankSpacing': 55}}}%%\n"
)


def mmd(source: str) -> str:
    return MMD_HEADER + MERMAID_INIT + dedent(source).strip() + '\n'


def markdown(source: str) -> str:
    return README_HEADER + dedent(source).lstrip().rstrip() + '\n'


def outputs() -> dict[str, str]:
    return {
        '01-system-context.mmd': mmd(
            '''
            flowchart TB
                subgraph players["Player personas"]
                    direction LR
                    field["<b>Field Explorer</b><br/>[Person]<br/>Enjoys place-based discovery, nature, and Niantic-style movement"]
                    cozy["<b>Cozy Cultivator</b><br/>[Person]<br/>Enjoys gentle routines, collecting, Home, and Town relationships"]
                    progress["<b>Patient Progressor</b><br/>[Person]<br/>Enjoys long-horizon mastery, idle progress, and completion"]
                    community["<b>Community Regular</b><br/>[Person]<br/>Enjoys shared spaces, light cooperation, and recurring rituals"]
                end
                jeremy["<b>Jeremy</b><br/>[Developer and Sole Director]<br/>Designs, builds, operates, and directs EarthNova"]
                earthnova["<b>EarthNova</b><br/>[Software System]<br/>A cozy real-world game for exploration, collection,<br/>Home, Town, progression, and social systems"]
                maps["<b>Map and geospatial providers</b><br/>[External Systems]<br/>Serve tiles, glyphs, and geography"]
                enrichment["<b>Content enrichment providers</b><br/>[External Systems]<br/>Serve language and image APIs to the live legacy queue"]
                ntfy["<b>ntfy</b><br/>[External System]<br/>Receives pipeline-health summaries"]

                field --> earthnova
                cozy --> earthnova
                progress --> earthnova
                community --> earthnova
                jeremy --> earthnova
                earthnova --> maps
                earthnova --> enrichment
                earthnova --> ntfy

                class field,cozy,progress,community,jeremy person
                class earthnova system
                class maps,enrichment,ntfy external
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef system fill:#1168bd,color:#ffffff,stroke:#0b4884,stroke-width:3px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '02-container.mmd': mmd(
            '''
            flowchart TB
                player["<b>Player</b><br/>[Person]<br/>Explores, collects, and uses EarthNova"]
                web["<b>Static Web Host</b><br/>[Container: Railway + nginx]<br/>Serves the versioned Flutter SPA"]
                client["<b>Flutter Web Client</b><br/>[Container: Flutter + Riverpod + MapLibre]<br/>UI, readiness, canonical position, gameplay slices"]
                working[("<b>Local State and Sync</b><br/>[Container: SharedPreferences]<br/>Bounded Player Save plus durable Identification recovery")]
                supabase["<b>Supabase Runtime</b><br/>[Container Group]<br/>Auth, PostgREST, Edge Functions, PostgreSQL/PostGIS, Storage"]
                maps["<b>Map providers</b><br/>[External Systems]<br/>Tiles and glyphs"]
                operations["<b>Operational providers</b><br/>[External Systems]<br/>Geography, enrichment, and health APIs"]

                player --> web
                web --> client
                client --> working
                client --> supabase
                client --> maps
                supabase --> operations

                class player person
                class web,client,supabase container
                class working database
                class maps,operations external
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef container fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef database fill:#2f95c8,color:#ffffff,stroke:#1d5f7d,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '02c-container-target.mmd': mmd(
            '''
            flowchart TB
                player["<b>Player</b><br/>[Person]<br/>Explores, collects, builds Home, visits Town, and joins social play"]
                app["<b>Player App</b><br/>[Target responsibility · device trust boundary]<br/>Immediate local gameplay presentation"]
                local[("<b>Local State and Sync</b><br/>[Target responsibility]<br/>Atomic complete saves, revision ancestry, checkpoints, conflicts, recovery")]
                api["<b>Identity and Game API</b><br/>[Target responsibility · authenticated API trust boundary]<br/>Authentication, validation, revision acceptance, authorized projections"]
                world[("<b>Game World Store</b><br/>[Target responsibility]<br/>Accepted saves, revision history, shared world, durable interactions")]
                background["<b>Background World Services</b><br/>[Target responsibility]<br/>Asynchronous interactions, reconciliation, telemetry, enrichment, health"]
                assets[("<b>Asset Delivery</b><br/>[Target responsibility]<br/>Static and generated art delivery")]
                providers["<b>External providers</b><br/>[External systems]<br/>Maps, geography, language, image, and notification APIs"]

                player --> app
                app --> local
                app --> api
                app --> assets
                api --> world
                background --> world
                background --> assets
                app --> providers
                background --> providers

                class player person
                class app,api,background container
                class local,world,assets database
                class providers external
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef container fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef database fill:#2f95c8,color:#ffffff,stroke:#1d5f7d,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '02a-container-supabase.mmd': mmd(
            '''
            flowchart LR
                client["<b>Flutter Web Client</b><br/>[External Container]"]
                operations["<b>Operational providers</b><br/>[External Systems]<br/>Geography, enrichment, and health APIs"]

                subgraph supabase["Supabase Runtime [Container Group]"]
                    direction LR
                    auth["<b>Identity</b><br/>[Container: Supabase Auth]<br/>Phone-derived password sessions"]
                    api["<b>Data API and RPC Gateway</b><br/>[Container: PostgREST]<br/>RLS projections and authenticated commands"]
                    edge["<b>Edge Functions</b><br/>[Container: Supabase Deno]<br/>Telemetry, scoped writes, provider calls"]
                    db[("<b>Game Database</b><br/>[Container: PostgreSQL + PostGIS]<br/>Production source of truth; v3 and legacy coexist")]
                    assets[("<b>Asset Delivery</b><br/>[Container: Supabase Storage]<br/>Public static and generated species art")]

                    api --> db
                    edge --> db
                end

                client --> auth
                client --> api
                client --> edge
                client --> assets
                edge --> operations
                edge --> assets

                class client,operations external
                class auth,api,edge container
                class db,assets database
                classDef container fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef database fill:#2f95c8,color:#ffffff,stroke:#1d5f7d,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                style supabase fill:#f8fafc,stroke:#64748b,stroke-width:2px,stroke-dasharray:6 4,color:#0f172a;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '02b-container-species-art.mmd': mmd(
            '''
            flowchart LR
                edge["<b>Enrichment Edge Function</b><br/>[Container: Supabase Deno]<br/>Requests generated art and uploads it"]
                provider["<b>Image provider</b><br/>[External System]<br/>Returns generated image bytes"]
                storage[("<b>Species Art Storage</b><br/>[Container: Supabase Storage]<br/>Public generated image assets")]
                client["<b>Flutter Web Client</b><br/>[External Container]<br/>Loads public image URLs"]

                edge --> provider
                edge --> storage
                storage --> client

                class edge container
                class storage database
                class provider,client external
                classDef container fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef database fill:#2f95c8,color:#ffffff,stroke:#1d5f7d,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '03-component-flutter-lifecycle.mmd': mmd(
            '''
            flowchart TB
                explorer["<b>Explorer</b><br/>[Person]<br/>Signs in and navigates"]
                platform["<b>Supabase Platform</b><br/>[External Containers]<br/>Auth, Data API/RPC, Telemetry Ingest"]
                browser[("<b>Browser Storage</b><br/>[External Container]")]

                subgraph client["Flutter Web Client [Container]"]
                    direction TB
                    lifecycle["<b>Application Lifecycle</b><br/>[Component]<br/>Bootstrap, adapter selection, ProviderScope, observability start"]
                    auth_component["<b>Auth and Session</b><br/>[Component]<br/>Normalize phone and call Supabase Auth"]
                    readiness["<b>App Readiness</b><br/>[Component]<br/>Refresh projections and gate startup"]
                    working[("<b>Local State and Sync</b><br/>[Component]<br/>Commit/hydrate snapshots; persist and replay safe commands")]
                    adapters["<b>Repository Adapters</b><br/>[Component]<br/>Call Supabase reads and commands"]
                    shell["<b>Tab Shell</b><br/>[Component]<br/>Map, Pack, Settings, transitions, wake lock"]
                    observability["<b>Observability</b><br/>[Component]<br/>Flush startup, screen, interaction, error logs/spans"]

                    lifecycle --> auth_component
                    auth_component --> readiness
                    readiness --> shell
                    readiness --> working
                    readiness --> adapters
                    shell --> observability
                end

                explorer --> lifecycle
                auth_component --> platform
                adapters --> platform
                observability --> platform
                working --> browser

                class explorer person
                class lifecycle,auth_component,readiness,working,shell,adapters,observability component
                class platform external
                class browser database
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef component fill:#85bbf0,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                classDef database fill:#dbeafe,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                style client fill:#f8fafc,stroke:#64748b,stroke-width:2px,stroke-dasharray:6 4,color:#0f172a;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '04-component-flutter-gameplay.mmd': mmd(
            '''
            flowchart LR
                explorer["<b>Explorer</b><br/>[Person]<br/>Navigates and supplies GPS or arrow/WASD input"]
                supabase["<b>Supabase Data API/RPC</b><br/>[External Container]"]
                maps["<b>Map providers</b><br/>[External Systems]<br/>Exploration tiles and glyphs"]

                subgraph client["Flutter Web Client [Container]"]
                    direction LR
                    shell["<b>Navigation Shell</b><br/>[Component]<br/>Map and Pack routes"]
                    position["<b>Canonical Position Input</b><br/>[Component]<br/>GPS/Desktop Traversal using browser APIs"]
                    exploration["<b>Exploration</b><br/>[Component]<br/>Map hierarchy, Cells, trusted entry, Visits, Encounter coordination"]
                    items["<b>Item Knowledge</b><br/>[Component]<br/>Pack, rewards, examination, prepared identification"]
                    projections["<b>Living World and Other Projections</b><br/>[Component]<br/>Town loads independently in Map; Index/Home are not surfaced"]
                    gateways["<b>Domain Repository Gateways</b><br/>[Component]<br/>All Supabase slice reads and RPC commands"]

                    shell --> exploration
                    shell --> items
                    position --> exploration
                    exploration --> items
                    exploration --> projections
                    exploration --> gateways
                    gateways --> projections
                end

                explorer --> shell
                explorer --> position
                exploration --> maps
                gateways --> supabase

                class explorer person
                class shell,position,exploration,items,projections,gateways component
                class supabase,maps external
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef component fill:#85bbf0,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                style client fill:#f8fafc,stroke:#64748b,stroke-width:2px,stroke-dasharray:6 4,color:#0f172a;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '05-component-supabase-gameplay.mmd': mmd(
            '''
            flowchart LR
                client["<b>Flutter Web Client</b><br/>[External Container]<br/>Sends sessions, reads, and commands"]
                api["<b>PostgREST</b><br/>[External Container]<br/>Authenticates JWT and exposes RLS views/RPCs"]

                subgraph postgres["PostgreSQL/PostGIS [Container]"]
                    direction LR
                    rpc["<b>Gameplay RPC Boundary</b><br/>[Component]<br/>Security-definer commands, grants, profile trigger, RLS projections"]
                    exploration["<b>Exploration Persistence</b><br/>[Component]<br/>Visits, selected-candidate validation/persistence, atomic Outcomes"]
                    knowledge["<b>Player Knowledge</b><br/>[Component]<br/>Items, Discovery, identification, Item Index, Town, Venue Visit, Home, disciplines"]
                    world["<b>Versioned World Model</b><br/>[Component]<br/>Immutable versions, Conditions, Selectors, map hierarchy"]
                    data[("<b>EarthNova Tables and Views</b><br/>[Data Store]<br/>Exact-version durable state; additive v3/legacy coexistence")]

                    rpc --> exploration
                    rpc --> knowledge
                    rpc --> world
                    exploration --> world
                    knowledge --> world
                    world --> data
                end

                client --> api
                api --> rpc

                class client,api external
                class rpc,exploration,knowledge,world component
                class data database
                classDef component fill:#85bbf0,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                classDef database fill:#2f95c8,color:#ffffff,stroke:#1d5f7d,stroke-width:2px;
                style postgres fill:#f8fafc,stroke:#64748b,stroke-width:2px,stroke-dasharray:6 4,color:#0f172a;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '06-component-supabase-operations.mmd': mmd(
            '''
            flowchart LR
                client["<b>Flutter Web Client</b><br/>[External Container]<br/>Sends telemetry envelopes"]
                cron["<b>pg_cron + pg_net</b><br/>[External Scheduler]<br/>Schedules processing, health, cleanup, retention"]
                operational_data[("<b>Operational Data</b><br/>[External Container: PostgreSQL]<br/>Logs/spans, views, enrichment events; 14-day retention")]
                game_data[("<b>Game and Geography Data</b><br/>[External Container: PostgreSQL/PostGIS]")]
                providers["<b>Operational providers</b><br/>[External Systems]<br/>Nominatim, language/image APIs, ntfy"]

                subgraph edge["Supabase Edge Functions [Container]"]
                    direction LR
                    telemetry["<b>Telemetry Ingest</b><br/>[Component]<br/>Validate envelopes and insert logs/spans"]
                    processing["<b>Geospatial and Legacy Processing</b><br/>[Component]<br/>Geography, enrichment, validation"]
                    health["<b>Pipeline Health</b><br/>[Component]<br/>Coverage, errors, stalls, notifications"]
                end

                client --> telemetry
                cron --> processing
                cron --> health
                cron --> operational_data
                telemetry --> operational_data
                processing --> operational_data
                processing --> game_data
                processing --> providers
                health --> operational_data
                health --> providers

                class client,cron,operational_data,game_data,providers external
                class telemetry,processing,health component
                classDef component fill:#85bbf0,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                style edge fill:#f8fafc,stroke:#64748b,stroke-width:2px,stroke-dasharray:6 4,color:#0f172a;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '07-dynamic-exploration-mode-transition.mmd': mmd(
            '''
            sequenceDiagram
                actor Explorer
                participant Client as Flutter Client
                participant Mode as Encounter Engine Gate
                participant Runtime as Selected Runtime

                Explorer->>Client: GPS update or arrow/WASD movement
                Note over Client: One canonical Player Position, Desktop only changes input
                Client->>Mode: Persist or recover Cell entry and resolve effective mode
                alt legacy, production default
                    Mode->>Runtime: Execute legacy Visit and Encounter writes
                else shadowPlanning
                    Mode->>Runtime: Compare v3 plan but execute legacy writes
                else v3Authoritative with verified writes authorized
                    Mode->>Runtime: Execute exact-version v3 flow
                end
                Runtime-->>Client: None, pending, resolved, or failed result
                Client-->>Explorer: Route and present Pack, Town, choices, or feedback
            '''
        ),
        '07a-dynamic-exploration-v3.mmd': mmd(
            '''
            flowchart LR
                client["<b>1. Flutter Client</b><br/>Persist trusted Cell entry"]
                visit["<b>2. record_v3_cell_visit</b><br/>Commit exact-version Visit binding"]
                planner["<b>3. Client Selector / Coordinator</b><br/>Select zero-or-one versioned candidate"]
                choice{"<b>4. Selection result</b>"}
                none["<b>5a. No Encounter</b><br/>Return no result"]
                manual["<b>5b. Manual Encounter</b><br/>Commit selection and return pending choices"]
                automatic["<b>5c. Automatic Encounter</b><br/>Commit selected Encounter"]
                outcomes["<b>6c. Automatic Outcomes</b><br/>Commit ordered Outcomes atomically"]
                result["<b>7c. Client result</b><br/>Route Item, Venue, no result, or failure<br/>Generated Items retain exact authored versions"]

                client --> visit
                visit --> planner
                planner --> choice
                choice --> none
                choice --> manual
                choice --> automatic
                automatic --> outcomes
                outcomes --> result

                class client,planner component
                class visit,manual,automatic,outcomes service
                class none,result result
                classDef component fill:#85bbf0,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef service fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef result fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                style choice fill:#fef3c7,color:#0f172a,stroke:#b45309,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '08-dynamic-item-examination.mmd': mmd(
            '''
            sequenceDiagram
                autonumber
                actor Explorer
                participant Pack as Pack UI / ItemsNotifier
                participant Sync as Local State and Sync
                participant Adapter as Identification Repository
                participant Commands as Item RPCs
                participant DB as PostgreSQL

                Explorer->>Pack: Examine an owned unexamined Item
                Pack->>Adapter: Examine Item ID
                Adapter->>Commands: examine_v3_item
                Commands->>DB: Lock Item and create or reuse exact-version journal entry
                DB-->>Commands: Examined state projection with identity hidden
                Commands-->>Adapter: Examined but unidentified Item
                Adapter-->>Pack: Reload newest-first Pack
                Pack-->>Explorer: Show examined evidence and safe hints, identity remains hidden
                Explorer->>Pack: Open Identification Service
                Pack->>Adapter: Prepare Identification
                Adapter->>Commands: prepare_v3_item_identification
                Commands->>DB: Verify examination, exact versions, known Villager Service
                DB-->>Commands: Prepared identities and Properties
                Commands-->>Adapter: Identification plan
                Adapter-->>Pack: Prepared plan
                Explorer->>Pack: Hold to reveal
                Pack->>Sync: Commit prepared plan
                Sync->>Sync: Persist a complete local save before dispatch
                Sync->>Adapter: Dispatch same command identity and plan
                Adapter->>Commands: identify_v3_item with expected identities
                Commands->>DB: Commit first Identification Discovery and Property values
                DB-->>Commands: Identified Item and durable Discovery
                Commands-->>Adapter: Canonical committed aggregate or idempotent replay
                Adapter-->>Sync: Canonical result
                Sync->>Pack: Apply identified Item
                Sync->>Sync: Persist receipt and include it in the next checkpoint
            '''
        ),
        '09-dynamic-app-readiness.mmd': mmd(
            '''
            sequenceDiagram
                actor Explorer
                participant App as Application Lifecycle
                participant Auth as Auth Notifier
                participant Ready as App Readiness Gate
                participant Cache as Player Save
                participant Sync as Checkpoint Coordinator
                participant API as Supabase API/RPC
                participant Shell as Tab Shell

                Explorer->>App: Load web application
                App->>Auth: Restore or refresh session
                Auth->>API: Validate session
                API-->>Auth: Authenticated Player
                Auth->>Ready: Start readiness
                Ready->>Cache: Load last bounded snapshot
                Ready->>Sync: Validate Player/environment queue
                Cache-->>Ready: Valid snapshot or missing
                alt valid warm snapshot
                    Ready->>Shell: Hydrate and release usable session
                    Ready->>API: Background refresh
                    API-->>Ready: Refresh result
                    Ready->>Cache: Commit successful refresh
                    Ready->>Sync: Reconcile deliveries and upload a whole-save checkpoint
                else cold start without valid snapshot
                    Ready->>API: Required cold-start fetch
                    API-->>Ready: Cold-start result
                    Ready->>Cache: Commit first valid snapshot
                    Ready->>Shell: Release cold-start session
                    Ready->>Sync: Reconcile deliveries and upload a whole-save checkpoint
                end
                Shell-->>App: Usable session
                App-->>Explorer: Render usable session
                Note over Ready,Shell: Warm refresh failure keeps the snapshot, input and Pack examination remain available
            '''
        ),
        '13-dynamic-checkpoint-acceptance.mmd': mmd(
            '''
            sequenceDiagram
                actor Player
                participant App as Player App
                participant Save as Local State and Sync
                participant API as Identity and Game API
                participant Store as Game World Store
                Player->>App: Complete gameplay action
                App->>Save: Atomically persist complete local save
                Save-->>Player: Saved on this device
                Save->>API: Submit checkpoint + ancestor + evidence
                API->>Store: Authenticate owner, lock head, validate state/progression
                alt duplicate checkpoint
                    Store-->>API: Existing accepted revision
                else exact ancestor and valid
                    Store->>Store: Atomically assign server revision and publish
                    Store-->>API: Accepted revision
                else stale ancestor
                    Store-->>API: Whole-save conflict + cloud revision
                else invalid evidence/state
                    Store-->>API: Defined rejection
                end
                API-->>Save: Result
                Note over Save: Confirmation never overwrites newer local work
            '''
        ),
        '14-dynamic-whole-save-conflict.mmd': mmd(
            '''
            sequenceDiagram
                actor Player
                participant App as Player App
                participant Save as Local State and Sync
                participant API as Identity and Game API
                App->>Save: Receive divergent accepted cloud save
                Save-->>Player: Show local/cloud progress summaries and consequences
                alt select local
                    Save->>Save: Preserve cloud branch
                    Save->>API: Reconcile receipts and validate local checkpoint against ancestry
                else select cloud
                    Save->>Save: Preserve local branch, atomically install cloud
                    Save->>API: Fetch later shared deliveries
                end
                API-->>Save: Accepted, conflict, or reconciliation required
                Save-->>Player: Saved / syncing / recovery state
            '''
        ),
        '15-dynamic-asynchronous-interaction.mmd': mmd(
            '''
            sequenceDiagram
                participant Service as Background World Services
                participant Store as Game World Store
                participant API as Identity and Game API
                participant Save as Local State and Sync
                Service->>Store: Claim pending interaction idempotently
                Store->>Store: Load exact accepted participant revisions
                Service->>Service: Process explicit rules version
                Service->>Store: Atomically record outcome and unique deliveries
                Save->>API: Fetch deliveries after server cursor
                API->>Store: Authorized Player delivery projection
                Store-->>Save: Ordered at-least-once deliveries
                Save->>Save: Apply each interaction ID once and persist receipt
                Note over Store,Save: Restoration cannot erase completed obligations or duplicate effects
            '''
        ),
        '16-dynamic-save-recovery.mmd': mmd(
            '''
            sequenceDiagram
                actor Player
                participant App as Player App
                participant Save as Local State and Sync
                participant DB as IndexedDB / app-support database
                participant API as Identity and Game API
                App->>Save: Restore Player/environment partition
                Save->>DB: Validate primary envelope and checksum
                alt valid primary
                    DB-->>Save: Primary
                else corrupt primary
                    Save->>DB: Validate transactional backup
                    DB-->>Save: Backup + recovery state
                else evicted or absent
                    Save->>API: Authenticated bootstrap/latest accepted save
                    API-->>Save: Complete safe projection or failure
                end
                Save->>DB: Atomic replacement
                Save-->>Player: Usable, recovery, or retry/sign-out state
            '''
        ),
        '10-deployment-delivery.mmd': mmd(
            '''
            flowchart TB
                operator["<b>Operator</b><br/>[Person]<br/>Authors, reviews, merges, and owns deployment policy"]
                tooling["<b>Local environment</b><br/>[Deployment Node: mise]<br/>Managed authoring, validation, and import toolchain"]
                repo["<b>geo-app revision</b><br/>[Artifact: GitHub repository]<br/>Code, migrations, functions, generated C4, tests, ADRs"]
                checks["<b>CI workflow</b><br/>[Build Process: GitHub Actions]<br/>Push and pull-request analysis, architecture checks, coverage"]
                deploy["<b>deploy-prod workflow</b><br/>[Deployment Process: GitHub Actions]<br/>Deploys the exact successful main-push CI head SHA<br/>Manual exact-SHA rollback remains available"]
                targets["<b>Production targets</b><br/>[Deployment Nodes]<br/>Migrations, then every Edge Function, then Railway nginx"]

                operator --> tooling
                tooling --> repo
                repo --> checks
                checks -->|Successful push CI on main| deploy
                operator -.->|Manual recovery or rollback| deploy
                deploy --> targets

                class operator person
                class repo artifact
                class checks,deploy process
                class tooling,targets deployment
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef artifact fill:#dbeafe,color:#0f172a,stroke:#3978a8,stroke-width:2px;
                classDef process fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef deployment fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '11-deployment-prod-runtime.mmd': mmd(
            '''
            flowchart LR
                explorer["<b>Explorer</b><br/>[Person]<br/>Opens the production URL"]
                railway["<b>Railway prod</b><br/>[Deployment Node]<br/>nginx serves the production Flutter bundle"]
                device["<b>Explorer device</b><br/>[Deployment Node]<br/>Browser runs Flutter and persists its atomic whole save"]
                supabase["<b>Supabase prod project</b><br/>[Deployment Node]<br/>Auth, API/RPC, Storage, Edge Functions, automation, PostgreSQL/PostGIS"]
                providers["<b>External providers</b><br/>[External Systems]<br/>Maps, geography, LLM/images, ntfy"]

                explorer --> railway
                railway --> device
                device --> supabase
                device --> providers
                supabase --> providers

                class explorer person
                class railway,device,supabase deployment
                class providers external
                classDef person fill:#084c61,color:#ffffff,stroke:#063c4d,stroke-width:2px;
                classDef deployment fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        '12-deployment-local-runtime.mmd': mmd(
            '''
            flowchart LR
                local["<b>Local environment</b><br/>[Deployment Node]<br/>mise-managed Flutter Chrome client persists its atomic whole save"]
                supabase["<b>Supabase prod project</b><br/>[Deployment Node]<br/>Local client uses production Auth, API/RPC, Storage, Edge Functions, PostgreSQL/PostGIS"]
                providers["<b>External providers</b><br/>[External Systems]<br/>Local client uses production map/geography providers"]

                local --> supabase
                local --> providers
                supabase --> providers

                class local,supabase deployment
                class providers external
                classDef deployment fill:#438dd5,color:#ffffff,stroke:#1d5f9b,stroke-width:2px;
                classDef external fill:#e2e8f0,color:#0f172a,stroke:#64748b,stroke-width:2px;
                linkStyle default stroke:#475569,color:#0f172a,stroke-width:1.5px;
            '''
        ),
        'README.md': markdown(
            '''
            # EarthNova C4 Architecture

            > **Role: CURRENT-SCOPED.** Current views describe observed runtime architecture; the separately labeled target view describes approved responsibility boundaries, not separate deployment processes. They do not override `CONTEXT.md`, accepted `docs/adr/`, or a current approved Outcome Contract.

            These files are generated, not inferred at runtime. The generator is the single editable architecture model; generated files must not be hand-edited.

            ## Views

            | File | C4 view | Scope |
            |---|---|---|
            | [`01-system-context.mmd`](01-system-context.mmd) | System Context | Four Player personas, Jeremy as Developer and Sole Director, full-product EarthNova scope, and external systems |
            | [`02-container.mmd`](02-container.mmd) | Current Container | Current Flutter/Railway/Supabase/Sembast whole-save runtime and trust boundaries |
            | [`02a-container-supabase.mmd`](02a-container-supabase.mmd) | Container | Supabase Auth, PostgREST, Edge Functions, PostgreSQL/PostGIS, and operational providers |
            | [`02b-container-species-art.mmd`](02b-container-species-art.mmd) | Container | Generated-image provider, enrichment Edge Function, Supabase Storage, and public client delivery |
            | [`02c-container-target.mmd`](02c-container-target.mmd) | Target Container | Six approved software responsibility boundaries; no process or deployment split is implied |
            | [`03-component-flutter-lifecycle.mmd`](03-component-flutter-lifecycle.mmd) | Component | Flutter bootstrap, auth, readiness, persistence, integration, navigation, and observability |
            | [`04-component-flutter-gameplay.mmd`](04-component-flutter-gameplay.mmd) | Component | Map, position, Encounters, Pack, item knowledge, projections, and gateways |
            | [`05-component-supabase-gameplay.mmd`](05-component-supabase-gameplay.mmd) | Component | PostgreSQL/PostGIS gameplay RPC, persistence, versioned-world, knowledge, Item Index, Town, and Venue Visit components |
            | [`06-component-supabase-operations.mmd`](06-component-supabase-operations.mmd) | Component | Edge Function telemetry, processing, and health components with external scheduler, data, and providers |
            | [`07-dynamic-exploration-mode-transition.mmd`](07-dynamic-exploration-mode-transition.mmd) | Dynamic | Production-default legacy, shadow-planning, and gated v3-authoritative runtime selection |
            | [`07a-dynamic-exploration-v3.mmd`](07a-dynamic-exploration-v3.mmd) | Dynamic | Gated v3-authoritative Visit persistence, client selection, pending/manual, and automatic Outcome commits |
            | [`08-dynamic-item-examination.mmd`](08-dynamic-item-examination.mmd) | Dynamic | Exact-version examination journal followed by separate prepared Identification and first durable Discovery |
            | [`09-dynamic-app-readiness.mmd`](09-dynamic-app-readiness.mmd) | Dynamic | Warm hydration/background refresh and cold required-fetch readiness paths |
            | [`13-dynamic-checkpoint-acceptance.mmd`](13-dynamic-checkpoint-acceptance.mmd) | Dynamic | Atomic duplicate-safe acceptance, stale-ancestor conflict, and confirmation race |
            | [`14-dynamic-whole-save-conflict.mmd`](14-dynamic-whole-save-conflict.mmd) | Dynamic | Explicit whole-save branch selection and displaced-branch preservation |
            | [`15-dynamic-asynchronous-interaction.mmd`](15-dynamic-asynchronous-interaction.mmd) | Dynamic | Exact published revisions, rules-version processing, and idempotent delivery |
            | [`16-dynamic-save-recovery.mmd`](16-dynamic-save-recovery.mmd) | Dynamic | Primary/backup validation, eviction bootstrap, and recovery states |
            | [`10-deployment-delivery.mmd`](10-deployment-delivery.mmd) | Deployment | Guarded successful-main-CI exact-SHA deployment plus manual recovery and Supabase-before-Railway order |
            | [`11-deployment-prod-runtime.mmd`](11-deployment-prod-runtime.mmd) | Deployment | `prod` browser, Railway, Supabase runtime/storage, automation, and providers |
            | [`12-deployment-local-runtime.mmd`](12-deployment-local-runtime.mmd) | Deployment | `local` Flutter Chrome using production data, browser storage, Supabase, and providers |

            This is the complete maintained set of **20 diagrams**: System Context, Current and Target Container, Component, Dynamic, and Deployment views. The table above is the review contact sheet and authoritative count. Structural and decision views use Mermaid flowcharts with explicit C4 stereotypes and scope labels; sequential Dynamic views use Mermaid sequence diagrams. This avoids the experimental Mermaid C4 renderer's fixed-layout collisions while preserving C4 semantics. Per-class code diagrams are intentionally omitted because the maintained architecture seams are repository interfaces and vertical slices, not individual classes.

            ## Generate

            From the repository root:

            ```bash
            python3 scripts/generate_c4_diagrams.py
            python3 scripts/generate_c4_diagrams.py --check
            ```

            The first command writes every file in this directory. `--check` makes no changes and exits non-zero when a generated file is missing, stale, or unexpected.

            Render one view with the existing renderer:

            ```bash
            ./scripts/render-mmd.sh docs/c4/01-system-context.mmd /tmp/earthnova-c4-context.png
            ```

            ## Evidence boundary

            The generator model was formed from:

            - `AGENTS.md`, `CONTEXT.md`, accepted `docs/adr/` records, and tracked `.agents/` decisions and history;
            - `lib/main.dart`, `lib/app/readiness/`, and implemented vertical slices under `lib/features/`;
            - `supabase/migrations/`, `supabase/functions/`, and the Flutter Supabase repository adapters;
            - `Dockerfile`, `nginx.conf`, `.github/workflows/`, `mise.toml`, `features/`, `product/`, and focused tests.

            Historical diagrams and aspirational Motivation/Multiplayer/world-event catalogs were excluded. Legacy tables and enrichment are shown only where live code, migrations, or scheduled functions still use them. The exact bounded-context partition remains deliberately unresolved, so the target containers are responsibility seams that can remain co-deployed; they do not settle the final domain map.
            '''
        ),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Generate the current EarthNova Mermaid C4 architecture set.',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Exit non-zero when committed generated files are missing or stale.',
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    generated = outputs()
    expected = set(generated)

    if args.check:
        stale = [
            name
            for name, content in generated.items()
            if not (OUTPUT_DIR / name).is_file()
            or (OUTPUT_DIR / name).read_text(encoding='utf-8') != content
        ]
        unexpected = (
            sorted(
                path.name
                for path in OUTPUT_DIR.iterdir()
                if path.is_file() and path.name not in expected
            )
            if OUTPUT_DIR.is_dir()
            else []
        )
        if stale or unexpected:
            if stale:
                print('Stale generated C4 files:')
                for name in stale:
                    print(f'  {OUTPUT_DIR.relative_to(ROOT) / name}')
            if unexpected:
                print('Unexpected generated C4 files:')
                for name in unexpected:
                    print(f'  {OUTPUT_DIR.relative_to(ROOT) / name}')
            return 1
        print(f'C4 diagrams are current ({len(generated)} files).')
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, content in generated.items():
        path = OUTPUT_DIR / name
        if not path.is_file() or path.read_text(encoding='utf-8') != content:
            path.write_text(content, encoding='utf-8')
            changed.append(name)

    for path in OUTPUT_DIR.iterdir():
        if path.is_file() and path.name not in expected:
            path.unlink()

    print(
        f'Generated {len(generated)} C4 files in {OUTPUT_DIR.relative_to(ROOT)}'
        f' ({len(changed)} changed).'
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
