-- Cell geometry substrate data model.
--
-- This is the backend source-of-truth foundation for GPS-cell fog rendering:
-- imported/generated Voronoi geometry is staged, validated as a complete
-- tessellation batch, then published by atomically switching the active version.

CREATE EXTENSION IF NOT EXISTS postgis;

-- Immutable generation/import batch metadata. A source_version represents one
-- complete candidate tessellation for the map cells in cell_properties.
CREATE TABLE cell_geometry_versions (
  source_version      TEXT PRIMARY KEY,
  source              TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'staged'
    CHECK (status IN ('staged', 'validating', 'validated', 'active', 'retired', 'rejected')),
  expected_cell_count INTEGER NOT NULL CHECK (expected_cell_count > 0),
  coverage_geom       geometry(MultiPolygon, 4326) NOT NULL,
  coverage_area_m2    DOUBLE PRECISION NOT NULL CHECK (coverage_area_m2 > 0),
  artifact_uri        TEXT,
  artifact_sha256     TEXT,
  validation_summary  JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  validated_at        TIMESTAMPTZ,
  activated_at        TIMESTAMPTZ,
  CHECK (NOT ST_IsEmpty(coverage_geom)),
  CHECK (ST_IsValid(coverage_geom))
);

-- Single-row active pointer. Publishing a validated source_version means
-- switching this row in one transaction; geometry rows remain immutable.
CREATE TABLE cell_geometry_active_version (
  singleton      BOOLEAN PRIMARY KEY DEFAULT true CHECK (singleton),
  source_version TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  activated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  activated_by   UUID REFERENCES auth.users(id)
);

-- Canonical immutable geometry rows for each version. Geometry is normalized to
-- MultiPolygon so the long-term RPC contract can expose polygons -> rings ->
-- points without changing storage later.
CREATE TABLE cell_geometry_cells (
  source_version TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  cell_id        TEXT NOT NULL REFERENCES cell_properties(cell_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  geom           geometry(MultiPolygon, 4326) NOT NULL,
  centroid       geometry(Point, 4326) NOT NULL,
  bbox           geometry(Polygon, 4326) NOT NULL,
  area_m2        DOUBLE PRECISION NOT NULL CHECK (area_m2 > 0),
  metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (source_version, cell_id),
  CHECK (NOT ST_IsEmpty(geom)),
  CHECK (ST_IsValid(geom)),
  CHECK (NOT ST_IsEmpty(centroid)),
  CHECK (NOT ST_IsEmpty(bbox))
);

-- Raw staging rows. Staging intentionally does not FK cell_id to
-- cell_properties and does not enforce one row per cell, so validation can
-- detect/report unknown cells, missing cells, and duplicates before publish.
CREATE TABLE cell_geometry_staging (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_version    TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  cell_id           TEXT,
  raw_payload       JSONB NOT NULL,
  raw_geometry      JSONB,
  raw_properties    JSONB NOT NULL DEFAULT '{}'::jsonb,
  parsed_geom       geometry(MultiPolygon, 4326),
  parsed_centroid   geometry(Point, 4326),
  parsed_bbox       geometry(Polygon, 4326),
  parsed_area_m2    DOUBLE PRECISION CHECK (parsed_area_m2 IS NULL OR parsed_area_m2 > 0),
  validation_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (validation_status IN ('pending', 'valid', 'warning', 'invalid')),
  validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cell_geometry_versions_status
  ON cell_geometry_versions(status);
CREATE INDEX idx_cell_geometry_versions_coverage_geom
  ON cell_geometry_versions USING GIST (coverage_geom);

CREATE INDEX idx_cell_geometry_cells_source_version
  ON cell_geometry_cells(source_version);
CREATE INDEX idx_cell_geometry_cells_cell_id
  ON cell_geometry_cells(cell_id);
CREATE INDEX idx_cell_geometry_cells_geom
  ON cell_geometry_cells USING GIST (geom);
CREATE INDEX idx_cell_geometry_cells_centroid
  ON cell_geometry_cells USING GIST (centroid);
CREATE INDEX idx_cell_geometry_cells_bbox
  ON cell_geometry_cells USING GIST (bbox);

CREATE INDEX idx_cell_geometry_staging_source_version
  ON cell_geometry_staging(source_version);
CREATE INDEX idx_cell_geometry_staging_cell_id
  ON cell_geometry_staging(cell_id)
  WHERE cell_id IS NOT NULL;
CREATE INDEX idx_cell_geometry_staging_validation_status
  ON cell_geometry_staging(source_version, validation_status);
CREATE INDEX idx_cell_geometry_staging_parsed_geom
  ON cell_geometry_staging USING GIST (parsed_geom)
  WHERE parsed_geom IS NOT NULL;

CREATE OR REPLACE VIEW cell_geometry_current AS
SELECT
  cells.source_version,
  cells.cell_id,
  cells.geom,
  cells.centroid,
  cells.bbox,
  cells.area_m2,
  cells.metadata,
  cells.created_at
FROM cell_geometry_cells cells
JOIN cell_geometry_active_version active
  ON active.source_version = cells.source_version;

ALTER TABLE cell_geometry_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cell_geometry_active_version ENABLE ROW LEVEL SECURITY;
ALTER TABLE cell_geometry_cells ENABLE ROW LEVEL SECURITY;
ALTER TABLE cell_geometry_staging ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read geometry versions"
  ON cell_geometry_versions FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service role can manage geometry versions"
  ON cell_geometry_versions FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can read active geometry version"
  ON cell_geometry_active_version FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service role can manage active geometry version"
  ON cell_geometry_active_version FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can read active geometry cells"
  ON cell_geometry_cells FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM cell_geometry_active_version active
      WHERE active.source_version = cell_geometry_cells.source_version
    )
  );

CREATE POLICY "Service role can manage geometry cells"
  ON cell_geometry_cells FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can manage geometry staging"
  ON cell_geometry_staging FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

GRANT SELECT ON cell_geometry_versions TO authenticated;
GRANT SELECT ON cell_geometry_active_version TO authenticated;
GRANT SELECT ON cell_geometry_cells TO authenticated;
GRANT SELECT ON cell_geometry_current TO authenticated;
GRANT ALL ON cell_geometry_versions TO service_role;
GRANT ALL ON cell_geometry_active_version TO service_role;
GRANT ALL ON cell_geometry_cells TO service_role;
GRANT ALL ON cell_geometry_staging TO service_role;
GRANT USAGE, SELECT ON SEQUENCE cell_geometry_staging_id_seq TO service_role;
