-- Cell geometry validation model.
--
-- Import/parsing is service-owned. Spatial/topology validation is DB-owned so
-- PostGIS remains the authority for whether a staged source_version can be
-- published as the active geometry tessellation.

CREATE TABLE cell_geometry_validation_runs (
  id                         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_version             TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  status                     TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'passed', 'failed', 'error')),
  overlap_area_epsilon_m2    DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (overlap_area_epsilon_m2 >= 0),
  gap_area_epsilon_m2        DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (gap_area_epsilon_m2 >= 0),
  summary                    JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at                TIMESTAMPTZ,
  created_by                 UUID REFERENCES auth.users(id)
);

CREATE TABLE cell_geometry_validation_issues (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id          UUID NOT NULL REFERENCES cell_geometry_validation_runs(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  source_version  TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  cell_id         TEXT,
  related_cell_id TEXT,
  severity        TEXT NOT NULL DEFAULT 'error'
    CHECK (severity IN ('error', 'warning', 'info')),
  code            TEXT NOT NULL,
  message         TEXT NOT NULL,
  details         JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cell_geometry_validation_runs_source_version
  ON cell_geometry_validation_runs(source_version, started_at DESC);
CREATE INDEX idx_cell_geometry_validation_runs_status
  ON cell_geometry_validation_runs(status);
CREATE INDEX idx_cell_geometry_validation_issues_run_id
  ON cell_geometry_validation_issues(run_id);
CREATE INDEX idx_cell_geometry_validation_issues_source_version
  ON cell_geometry_validation_issues(source_version);
CREATE INDEX idx_cell_geometry_validation_issues_code
  ON cell_geometry_validation_issues(code);
CREATE INDEX idx_cell_geometry_validation_issues_cell_id
  ON cell_geometry_validation_issues(cell_id)
  WHERE cell_id IS NOT NULL;

ALTER TABLE cell_geometry_validation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE cell_geometry_validation_issues ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can manage geometry validation runs"
  ON cell_geometry_validation_runs FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can manage geometry validation issues"
  ON cell_geometry_validation_issues FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE OR REPLACE FUNCTION validate_cell_geometry_source_version(
  p_source_version TEXT,
  p_overlap_area_epsilon_m2 DOUBLE PRECISION DEFAULT 1.0,
  p_gap_area_epsilon_m2 DOUBLE PRECISION DEFAULT 1.0
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_id UUID;
  v_expected_cell_count INTEGER;
  v_known_cell_count INTEGER;
  v_staged_row_count INTEGER;
  v_unique_staged_cell_count INTEGER;
  v_issue_count INTEGER;
  v_gap_area_m2 DOUBLE PRECISION := 0;
  v_overflow_area_m2 DOUBLE PRECISION := 0;
  v_summary JSONB;
BEGIN
  IF p_overlap_area_epsilon_m2 < 0 OR p_gap_area_epsilon_m2 < 0 THEN
    RAISE EXCEPTION 'Geometry validation epsilons must be non-negative';
  END IF;

  SELECT expected_cell_count
  INTO v_expected_cell_count
  FROM cell_geometry_versions
  WHERE source_version = p_source_version
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown cell geometry source_version: %', p_source_version;
  END IF;

  SELECT COUNT(*)::INTEGER
  INTO v_known_cell_count
  FROM cell_properties;

  SELECT COUNT(*)::INTEGER,
         COUNT(DISTINCT cell_id)::INTEGER
  INTO v_staged_row_count,
       v_unique_staged_cell_count
  FROM cell_geometry_staging
  WHERE source_version = p_source_version
    AND cell_id IS NOT NULL;

  INSERT INTO cell_geometry_validation_runs (
    source_version,
    overlap_area_epsilon_m2,
    gap_area_epsilon_m2,
    created_by
  )
  VALUES (
    p_source_version,
    p_overlap_area_epsilon_m2,
    p_gap_area_epsilon_m2,
    auth.uid()
  )
  RETURNING id INTO v_run_id;

  UPDATE cell_geometry_versions
  SET status = 'validating'
  WHERE source_version = p_source_version;

  IF v_expected_cell_count <> v_known_cell_count THEN
    INSERT INTO cell_geometry_validation_issues (
      run_id, source_version, code, message, details
    )
    VALUES (
      v_run_id,
      p_source_version,
      'expected_cell_count_mismatch',
      'Geometry version expected_cell_count must match the canonical cell_properties count.',
      jsonb_build_object(
        'expected_cell_count', v_expected_cell_count,
        'cell_properties_count', v_known_cell_count
      )
    );
  END IF;

  IF v_staged_row_count = 0 THEN
    INSERT INTO cell_geometry_validation_issues (
      run_id, source_version, code, message
    )
    VALUES (
      v_run_id,
      p_source_version,
      'no_staged_geometry',
      'No staged geometry rows exist for this source_version.'
    );
  END IF;

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    'missing_cell_id',
    'A staged geometry row is missing cell_id.',
    jsonb_build_object('staging_id', staging.id)
  FROM cell_geometry_staging staging
  WHERE staging.source_version = p_source_version
    AND staging.cell_id IS NULL;

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    staging.cell_id,
    'unknown_cell_id',
    'A staged geometry row references a cell_id not present in cell_properties.',
    jsonb_build_object('staging_id', staging.id)
  FROM cell_geometry_staging staging
  WHERE staging.source_version = p_source_version
    AND staging.cell_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM cell_properties cp
      WHERE cp.cell_id = staging.cell_id
    );

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    grouped.cell_id,
    'duplicate_cell_id',
    'A source_version must stage exactly one geometry row per cell_id.',
    jsonb_build_object('row_count', grouped.row_count)
  FROM (
    SELECT cell_id, COUNT(*)::INTEGER AS row_count
    FROM cell_geometry_staging
    WHERE source_version = p_source_version
      AND cell_id IS NOT NULL
    GROUP BY cell_id
    HAVING COUNT(*) > 1
  ) grouped;

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, code, message
  )
  SELECT
    v_run_id,
    p_source_version,
    cp.cell_id,
    'missing_expected_cell',
    'A cell_properties row has no staged geometry for this source_version.'
  FROM cell_properties cp
  WHERE NOT EXISTS (
    SELECT 1
    FROM cell_geometry_staging staging
    WHERE staging.source_version = p_source_version
      AND staging.cell_id = cp.cell_id
  );

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    staging.cell_id,
    'invalid_geometry',
    'A staged row has missing, empty, invalid, or non-4326 parsed geometry.',
    jsonb_build_object(
      'staging_id', staging.id,
      'has_parsed_geom', staging.parsed_geom IS NOT NULL,
      'is_empty', CASE WHEN staging.parsed_geom IS NULL THEN NULL ELSE ST_IsEmpty(staging.parsed_geom) END,
      'is_valid', CASE WHEN staging.parsed_geom IS NULL THEN NULL ELSE ST_IsValid(staging.parsed_geom) END,
      'srid', CASE WHEN staging.parsed_geom IS NULL THEN NULL ELSE ST_SRID(staging.parsed_geom) END
    )
  FROM cell_geometry_staging staging
  WHERE staging.source_version = p_source_version
    AND (
      staging.parsed_geom IS NULL
      OR ST_IsEmpty(staging.parsed_geom)
      OR NOT ST_IsValid(staging.parsed_geom)
      OR ST_SRID(staging.parsed_geom) <> 4326
    );

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    staging.cell_id,
    'invalid_derived_geometry_metadata',
    'A staged row is missing required derived geometry metadata.',
    jsonb_build_object(
      'staging_id', staging.id,
      'has_centroid', staging.parsed_centroid IS NOT NULL,
      'has_bbox', staging.parsed_bbox IS NOT NULL,
      'parsed_area_m2', staging.parsed_area_m2
    )
  FROM cell_geometry_staging staging
  WHERE staging.source_version = p_source_version
    AND (
      staging.parsed_centroid IS NULL
      OR staging.parsed_bbox IS NULL
      OR staging.parsed_area_m2 IS NULL
      OR staging.parsed_area_m2 <= 0
    );

  INSERT INTO cell_geometry_validation_issues (
    run_id, source_version, cell_id, related_cell_id, code, message, details
  )
  SELECT
    v_run_id,
    p_source_version,
    a.cell_id,
    b.cell_id,
    'geometry_overlap',
    'Two staged cells overlap beyond the configured epsilon.',
    jsonb_build_object('overlap_area_m2', overlap_calc.overlap_area_m2)
  FROM cell_geometry_staging a
  JOIN cell_geometry_staging b
    ON b.source_version = a.source_version
   AND b.id > a.id
  CROSS JOIN LATERAL (
    SELECT ST_Area(
      ST_CollectionExtract(ST_Intersection(a.parsed_geom, b.parsed_geom), 3)::geography
    ) AS overlap_area_m2
  ) overlap_calc
  WHERE a.source_version = p_source_version
    AND a.cell_id IS NOT NULL
    AND b.cell_id IS NOT NULL
    AND a.parsed_geom IS NOT NULL
    AND b.parsed_geom IS NOT NULL
    AND ST_IsValid(a.parsed_geom)
    AND ST_IsValid(b.parsed_geom)
    AND ST_Intersects(a.parsed_geom, b.parsed_geom)
    AND overlap_calc.overlap_area_m2 > p_overlap_area_epsilon_m2;

  WITH valid_union AS (
    SELECT ST_UnaryUnion(ST_Collect(staging.parsed_geom)) AS geom
    FROM cell_geometry_staging staging
    WHERE staging.source_version = p_source_version
      AND staging.cell_id IS NOT NULL
      AND staging.parsed_geom IS NOT NULL
      AND NOT ST_IsEmpty(staging.parsed_geom)
      AND ST_IsValid(staging.parsed_geom)
  ), coverage AS (
    SELECT coverage_geom
    FROM cell_geometry_versions
    WHERE source_version = p_source_version
  )
  SELECT
    COALESCE(ST_Area(ST_CollectionExtract(ST_Difference(coverage.coverage_geom, valid_union.geom), 3)::geography), 0),
    COALESCE(ST_Area(ST_CollectionExtract(ST_Difference(valid_union.geom, coverage.coverage_geom), 3)::geography), 0)
  INTO v_gap_area_m2,
       v_overflow_area_m2
  FROM coverage
  CROSS JOIN valid_union;

  IF v_gap_area_m2 > p_gap_area_epsilon_m2 THEN
    INSERT INTO cell_geometry_validation_issues (
      run_id, source_version, code, message, details
    )
    VALUES (
      v_run_id,
      p_source_version,
      'coverage_gap',
      'The staged geometry union does not fully cover the source_version coverage geometry.',
      jsonb_build_object('gap_area_m2', v_gap_area_m2)
    );
  END IF;

  IF v_overflow_area_m2 > p_gap_area_epsilon_m2 THEN
    INSERT INTO cell_geometry_validation_issues (
      run_id, source_version, code, message, details
    )
    VALUES (
      v_run_id,
      p_source_version,
      'coverage_overflow',
      'The staged geometry union extends outside the source_version coverage geometry.',
      jsonb_build_object('overflow_area_m2', v_overflow_area_m2)
    );
  END IF;

  SELECT COUNT(*)::INTEGER
  INTO v_issue_count
  FROM cell_geometry_validation_issues
  WHERE run_id = v_run_id
    AND severity = 'error';

  v_summary := jsonb_build_object(
    'known_cell_count', v_known_cell_count,
    'expected_cell_count', v_expected_cell_count,
    'staged_row_count', v_staged_row_count,
    'unique_staged_cell_count', v_unique_staged_cell_count,
    'error_count', v_issue_count,
    'gap_area_m2', v_gap_area_m2,
    'overflow_area_m2', v_overflow_area_m2,
    'overlap_area_epsilon_m2', p_overlap_area_epsilon_m2,
    'gap_area_epsilon_m2', p_gap_area_epsilon_m2
  );

  UPDATE cell_geometry_validation_runs
  SET status = CASE WHEN v_issue_count = 0 THEN 'passed' ELSE 'failed' END,
      summary = v_summary,
      finished_at = now()
  WHERE id = v_run_id;

  UPDATE cell_geometry_versions
  SET status = CASE WHEN v_issue_count = 0 THEN 'validated' ELSE 'rejected' END,
      validation_summary = v_summary,
      validated_at = CASE WHEN v_issue_count = 0 THEN now() ELSE validated_at END
  WHERE source_version = p_source_version;

  RETURN v_run_id;
EXCEPTION WHEN OTHERS THEN
  IF v_run_id IS NOT NULL THEN
    UPDATE cell_geometry_validation_runs
    SET status = 'error',
        summary = jsonb_build_object('error', SQLERRM),
        finished_at = now()
    WHERE id = v_run_id;
  END IF;
  UPDATE cell_geometry_versions
  SET status = 'rejected',
      validation_summary = jsonb_build_object('error', SQLERRM)
  WHERE source_version = p_source_version;
  RAISE;
END;
$$;

GRANT ALL ON cell_geometry_validation_runs TO service_role;
GRANT ALL ON cell_geometry_validation_issues TO service_role;
GRANT USAGE, SELECT ON SEQUENCE cell_geometry_validation_issues_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION validate_cell_geometry_source_version(
  TEXT,
  DOUBLE PRECISION,
  DOUBLE PRECISION
) TO service_role;
