ALTER TABLE cell_properties
  ADD COLUMN IF NOT EXISTS habitat_source TEXT NOT NULL DEFAULT 'legacy_unverified';

ALTER TABLE cell_properties
  ADD COLUMN IF NOT EXISTS habitat_source_version TEXT;

ALTER TABLE cell_properties
  ADD COLUMN IF NOT EXISTS habitat_confidence TEXT NOT NULL DEFAULT 'legacy_unverified';

ALTER TABLE cell_properties
  ADD COLUMN IF NOT EXISTS habitat_provenance JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE cell_properties
  ADD COLUMN IF NOT EXISTS habitat_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE cell_properties
  DROP CONSTRAINT IF EXISTS cell_properties_habitat_source_nonempty;

ALTER TABLE cell_properties
  ADD CONSTRAINT cell_properties_habitat_source_nonempty
  CHECK (btrim(habitat_source) <> '');

ALTER TABLE cell_properties
  DROP CONSTRAINT IF EXISTS cell_properties_habitat_confidence_check;

ALTER TABLE cell_properties
  ADD CONSTRAINT cell_properties_habitat_confidence_check
  CHECK (
    habitat_confidence IN (
      'legacy_unverified',
      'classified',
      'partial',
      'manual_override',
      'unclassified'
    )
  );

UPDATE cell_properties
SET habitat_source = 'legacy_unverified',
    habitat_confidence = 'legacy_unverified',
    habitat_provenance = CASE
      WHEN habitat_provenance = '{}'::jsonb THEN
        jsonb_build_object(
          'reason', 'pre-provenance legacy cell_properties row',
          'legacy_habitats', to_jsonb(habitats)
        )
      ELSE habitat_provenance
    END,
    habitat_updated_at = COALESCE(habitat_updated_at, created_at, now())
WHERE habitat_source = 'legacy_unverified'
   OR habitat_confidence = 'legacy_unverified'
   OR habitat_provenance = '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_cell_properties_habitat_confidence
  ON cell_properties (habitat_confidence);

CREATE INDEX IF NOT EXISTS idx_cell_properties_habitat_source_version
  ON cell_properties (habitat_source_version);

CREATE TABLE IF NOT EXISTS cell_habitat_source_versions (
  source_version TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  coverage_geom geometry(MultiPolygon, 4326) NOT NULL,
  feature_count INTEGER NOT NULL DEFAULT 0 CHECK (feature_count >= 0),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (NOT ST_IsEmpty(coverage_geom)),
  CHECK (ST_IsValid(coverage_geom))
);

CREATE INDEX IF NOT EXISTS idx_cell_habitat_source_versions_geom
  ON cell_habitat_source_versions USING GIST (coverage_geom);

CREATE TABLE IF NOT EXISTS cell_habitat_source_features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_version TEXT NOT NULL REFERENCES cell_habitat_source_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  feature_id TEXT NOT NULL,
  normalized_habitat TEXT NOT NULL CHECK (
    normalized_habitat IN (
      'forest',
      'ocean',
      'freshwater',
      'swamp',
      'desert',
      'plains',
      'urban',
      'mountain'
    )
  ),
  source_layer TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (weight > 0),
  source_properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  area_m2 DOUBLE PRECISION GENERATED ALWAYS AS (ST_Area(geom::geography)) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_version, feature_id),
  CHECK (NOT ST_IsEmpty(geom)),
  CHECK (ST_IsValid(geom))
);

CREATE INDEX IF NOT EXISTS idx_cell_habitat_source_features_source_habitat
  ON cell_habitat_source_features (source_version, normalized_habitat);

CREATE INDEX IF NOT EXISTS idx_cell_habitat_source_features_geom
  ON cell_habitat_source_features USING GIST (geom);

CREATE TABLE IF NOT EXISTS cell_habitat_classification_runs (
  run_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_version TEXT NOT NULL REFERENCES cell_habitat_source_versions(source_version)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  source TEXT NOT NULL,
  geometry_source_version TEXT NOT NULL REFERENCES cell_geometry_versions(source_version)
    ON UPDATE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('running', 'applied', 'failed')),
  parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_cell_habitat_classification_runs_source_version
  ON cell_habitat_classification_runs (source_version, started_at DESC);

CREATE TABLE IF NOT EXISTS cell_habitat_classification_results (
  run_id UUID NOT NULL REFERENCES cell_habitat_classification_runs(run_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  cell_id TEXT NOT NULL REFERENCES cell_properties(cell_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  selected_habitats TEXT[] NOT NULL,
  dominant_habitat TEXT,
  habitat_confidence TEXT NOT NULL CHECK (
    habitat_confidence IN (
      'classified',
      'partial',
      'manual_override',
      'unclassified'
    )
  ),
  coverage_ratio DOUBLE PRECISION NOT NULL CHECK (coverage_ratio >= 0 AND coverage_ratio <= 1),
  area_fractions JSONB NOT NULL DEFAULT '{}'::jsonb,
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (run_id, cell_id)
);

CREATE INDEX IF NOT EXISTS idx_cell_habitat_classification_results_cell
  ON cell_habitat_classification_results (cell_id, applied_at DESC);

CREATE OR REPLACE FUNCTION classify_cell_habitats_from_source_version(
  p_source_version TEXT,
  p_geometry_source_version TEXT DEFAULT NULL,
  p_cell_ids TEXT[] DEFAULT NULL,
  p_min_share DOUBLE PRECISION DEFAULT 0.18,
  p_partial_cover_threshold DOUBLE PRECISION DEFAULT 0.65
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_run_id UUID := gen_random_uuid();
  v_geometry_source_version TEXT;
  v_source TEXT;
BEGIN
  IF p_min_share <= 0 OR p_min_share > 1 THEN
    RAISE EXCEPTION 'p_min_share must be in (0,1], got %', p_min_share;
  END IF;

  IF p_partial_cover_threshold <= 0 OR p_partial_cover_threshold > 1 THEN
    RAISE EXCEPTION 'p_partial_cover_threshold must be in (0,1], got %', p_partial_cover_threshold;
  END IF;

  SELECT source
  INTO v_source
  FROM cell_habitat_source_versions
  WHERE source_version = p_source_version;

  IF v_source IS NULL THEN
    RAISE EXCEPTION 'Unknown cell habitat source_version: %', p_source_version;
  END IF;

  SELECT COALESCE(
    p_geometry_source_version,
    (
      SELECT active.source_version
      FROM cell_geometry_active_version active
      ORDER BY active.activated_at DESC NULLS LAST, active.source_version DESC
      LIMIT 1
    )
  )
  INTO v_geometry_source_version;

  IF v_geometry_source_version IS NULL THEN
    RAISE EXCEPTION 'No cell geometry source_version available for habitat classification';
  END IF;

  INSERT INTO cell_habitat_classification_runs (
    run_id,
    source_version,
    source,
    geometry_source_version,
    status,
    parameters
  )
  VALUES (
    v_run_id,
    p_source_version,
    v_source,
    v_geometry_source_version,
    'running',
    jsonb_build_object(
      'cell_ids', COALESCE(to_jsonb(p_cell_ids), 'null'::jsonb),
      'min_share', p_min_share,
      'partial_cover_threshold', p_partial_cover_threshold
    )
  );

  WITH source_meta AS (
    SELECT source_version, source, coverage_geom
    FROM cell_habitat_source_versions
    WHERE source_version = p_source_version
  ), target_cells AS (
    SELECT
      cp.cell_id,
      cg.geom,
      cg.area_m2 AS cell_area_m2,
      sm.source,
      sm.source_version AS habitat_source_version
    FROM cell_properties cp
    JOIN cell_geometry_cells cg
      ON cg.cell_id = cp.cell_id
     AND cg.source_version = v_geometry_source_version
    JOIN source_meta sm
      ON cg.geom && ST_Envelope(sm.coverage_geom)
     AND ST_Intersects(cg.geom, sm.coverage_geom)
    WHERE p_cell_ids IS NULL OR cp.cell_id = ANY(p_cell_ids)
  ), intersecting_features AS (
    SELECT
      cell.cell_id,
      cell.cell_area_m2,
      feature.normalized_habitat,
      SUM(
        ST_Area(
          ST_Intersection(cell.geom, feature.geom)::geography
        ) * feature.weight
      ) AS weighted_area_m2,
      COUNT(*)::INTEGER AS feature_count
    FROM target_cells cell
    JOIN cell_habitat_source_features feature
      ON feature.source_version = p_source_version
     AND feature.geom && cell.geom
     AND ST_Intersects(feature.geom, cell.geom)
    GROUP BY cell.cell_id, cell.cell_area_m2, feature.normalized_habitat
  ), ranked_features AS (
    SELECT
      raw.cell_id,
      raw.cell_area_m2,
      raw.normalized_habitat,
      raw.weighted_area_m2,
      raw.feature_count,
      raw.weighted_area_m2 / NULLIF(raw.cell_area_m2, 0) AS share,
      ROW_NUMBER() OVER (
        PARTITION BY raw.cell_id
        ORDER BY raw.weighted_area_m2 DESC, raw.normalized_habitat ASC
      ) AS habitat_rank
    FROM intersecting_features raw
    WHERE raw.weighted_area_m2 > 0
  ), selected_features AS (
    SELECT *
    FROM ranked_features
    WHERE share >= p_min_share OR habitat_rank = 1
  ), aggregated_cells AS (
    SELECT
      cell.cell_id,
      COALESCE(
        array_agg(selection.normalized_habitat ORDER BY selection.share DESC, selection.normalized_habitat)
          FILTER (WHERE selection.normalized_habitat IS NOT NULL),
        ARRAY[]::TEXT[]
      ) AS selected_habitats,
      (
        array_agg(selection.normalized_habitat ORDER BY selection.share DESC, selection.normalized_habitat)
          FILTER (WHERE selection.normalized_habitat IS NOT NULL)
      )[1] AS dominant_habitat,
      MAX(cell.cell_area_m2) AS cell_area_m2,
      COALESCE(SUM(selection.weighted_area_m2), 0) AS covered_area_m2,
      COALESCE(SUM(selection.feature_count), 0) AS feature_count,
      COALESCE(
        jsonb_object_agg(
          selection.normalized_habitat,
          jsonb_build_object(
            'share', ROUND(selection.share::NUMERIC, 6),
            'weighted_area_m2', ROUND(selection.weighted_area_m2::NUMERIC, 3),
            'feature_count', selection.feature_count
          )
        ) FILTER (WHERE selection.normalized_habitat IS NOT NULL),
        '{}'::jsonb
      ) AS area_fractions,
      MAX(cell.source) AS source,
      MAX(cell.habitat_source_version) AS habitat_source_version
    FROM target_cells cell
    LEFT JOIN selected_features selection
      ON selection.cell_id = cell.cell_id
    GROUP BY cell.cell_id
  ), final_rows AS (
    SELECT
      aggregated.cell_id,
      aggregated.selected_habitats,
      aggregated.dominant_habitat,
      COALESCE(aggregated.covered_area_m2 / NULLIF(aggregated.cell_area_m2, 0), 0) AS coverage_ratio,
      CASE
        WHEN array_length(aggregated.selected_habitats, 1) IS NULL THEN 'unclassified'
        WHEN COALESCE(aggregated.covered_area_m2 / NULLIF(aggregated.cell_area_m2, 0), 0) < p_partial_cover_threshold THEN 'partial'
        ELSE 'classified'
      END AS habitat_confidence,
      aggregated.area_fractions,
      jsonb_build_object(
        'source', aggregated.source,
        'source_version', aggregated.habitat_source_version,
        'geometry_source_version', v_geometry_source_version,
        'coverage_ratio', ROUND(COALESCE(aggregated.covered_area_m2 / NULLIF(aggregated.cell_area_m2, 0), 0)::NUMERIC, 6),
        'dominant_habitat', aggregated.dominant_habitat,
        'selected_habitats', to_jsonb(aggregated.selected_habitats),
        'feature_count', aggregated.feature_count,
        'shares', aggregated.area_fractions
      ) AS provenance
    FROM aggregated_cells aggregated
  )
  INSERT INTO cell_habitat_classification_results (
    run_id,
    cell_id,
    selected_habitats,
    dominant_habitat,
    habitat_confidence,
    coverage_ratio,
    area_fractions,
    provenance
  )
  SELECT
    v_run_id,
    final.cell_id,
    final.selected_habitats,
    final.dominant_habitat,
    final.habitat_confidence,
    final.coverage_ratio,
    final.area_fractions,
    final.provenance
  FROM final_rows final;

  UPDATE cell_properties cp
  SET habitats = result.selected_habitats,
      habitat_source = v_source,
      habitat_source_version = p_source_version,
      habitat_confidence = result.habitat_confidence,
      habitat_provenance = result.provenance,
      habitat_updated_at = now()
  FROM cell_habitat_classification_results result
  WHERE result.run_id = v_run_id
    AND result.cell_id = cp.cell_id;

  UPDATE cell_habitat_classification_runs run
  SET status = 'applied',
      summary = (
        SELECT jsonb_build_object(
          'cell_count', COUNT(*),
          'classified_count', COUNT(*) FILTER (WHERE habitat_confidence = 'classified'),
          'partial_count', COUNT(*) FILTER (WHERE habitat_confidence = 'partial'),
          'unclassified_count', COUNT(*) FILTER (WHERE habitat_confidence = 'unclassified'),
          'urban_count', COUNT(*) FILTER (WHERE 'urban' = ANY(selected_habitats))
        )
        FROM cell_habitat_classification_results
        WHERE run_id = v_run_id
      ),
      finished_at = now()
  WHERE run.run_id = v_run_id;

  RETURN v_run_id;
EXCEPTION
  WHEN OTHERS THEN
    UPDATE cell_habitat_classification_runs run
    SET status = 'failed',
        summary = jsonb_build_object('error', SQLERRM),
        finished_at = now()
    WHERE run.run_id = v_run_id;
    RAISE;
END;
$$;

GRANT EXECUTE ON FUNCTION classify_cell_habitats_from_source_version(
  TEXT,
  TEXT,
  TEXT[],
  DOUBLE PRECISION,
  DOUBLE PRECISION
) TO service_role;

DROP FUNCTION IF EXISTS fetch_nearby_cells(
  DOUBLE PRECISION,
  DOUBLE PRECISION,
  DOUBLE PRECISION
);

CREATE FUNCTION fetch_nearby_cells(
  p_lat DOUBLE PRECISION,
  p_lng DOUBLE PRECISION,
  p_radius_meters DOUBLE PRECISION DEFAULT 2000
)
RETURNS TABLE (
  cell_id TEXT,
  habitats TEXT[],
  polygon JSONB,
  polygons JSONB,
  district_id TEXT,
  city_id TEXT,
  state_id TEXT,
  country_id TEXT,
  habitat_source_version TEXT,
  habitat_confidence TEXT,
  geometry_source_version TEXT,
  geometry_generation_mode TEXT,
  centroid_dataset_version TEXT,
  geometry_contract TEXT,
  geometry_visual_quality JSONB
)
LANGUAGE SQL
STABLE
SECURITY INVOKER
AS $$
  WITH params AS (
    SELECT
      ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326) AS point_geom,
      p_radius_meters AS radius_meters,
      GREATEST(
        p_radius_meters / 110574.0,
        p_radius_meters / (
          111320.0 * GREATEST(abs(cos(radians(p_lat))), 0.01)
        )
      ) AS radius_degrees
  ), nearby_geometry AS (
    SELECT
      cell_geom.source_version,
      cell_geom.cell_id,
      cell_geom.geom,
      cell_geom.metadata
    FROM cell_geometry_current cell_geom
    CROSS JOIN params
    WHERE cell_geom.geom && ST_Expand(params.point_geom, params.radius_degrees)
      AND ST_DWithin(
        cell_geom.geom::geography,
        params.point_geom::geography,
        params.radius_meters
      )
  ), nearby_cells AS (
    SELECT
      cp.cell_id,
      cp.habitats,
      COALESCE(geometry_json.polygons->0->0, '[]'::jsonb) AS polygon,
      geometry_json.polygons,
      d.id AS district_id,
      c.id AS city_id,
      s.id AS state_id,
      country.id AS country_id,
      cp.habitat_source_version,
      cp.habitat_confidence,
      cell_geom.source_version AS geometry_source_version,
      cell_geom.metadata->>'generation_mode' AS geometry_generation_mode,
      cell_geom.metadata->>'centroid_dataset_version' AS centroid_dataset_version,
      cell_geom.metadata->>'geometry_contract' AS geometry_contract,
      versions.validation_summary->'visual_quality' AS geometry_visual_quality
    FROM nearby_geometry cell_geom
    JOIN cell_properties cp
      ON cp.cell_id = cell_geom.cell_id
    JOIN cell_geometry_versions versions
      ON versions.source_version = cell_geom.source_version
    CROSS JOIN LATERAL (
      SELECT cell_geometry_latlng_polygons_jsonb(cell_geom.geom) AS polygons
    ) geometry_json
    LEFT JOIN districts d ON d.id = cp.location_id
    LEFT JOIN cities c ON c.id = d.city_id
    LEFT JOIN states s ON s.id = c.state_id
    LEFT JOIN countries country ON country.id = s.country_id
  )
  SELECT
    nearby_cells.cell_id,
    nearby_cells.habitats,
    nearby_cells.polygon,
    nearby_cells.polygons,
    nearby_cells.district_id,
    nearby_cells.city_id,
    nearby_cells.state_id,
    nearby_cells.country_id,
    nearby_cells.habitat_source_version,
    nearby_cells.habitat_confidence,
    nearby_cells.geometry_source_version,
    nearby_cells.geometry_generation_mode,
    nearby_cells.centroid_dataset_version,
    nearby_cells.geometry_contract,
    nearby_cells.geometry_visual_quality
  FROM nearby_cells
  WHERE jsonb_typeof(nearby_cells.polygon) = 'array'
    AND jsonb_array_length(nearby_cells.polygon) >= 4;
$$;

GRANT EXECUTE ON FUNCTION fetch_nearby_cells(
  DOUBLE PRECISION,
  DOUBLE PRECISION,
  DOUBLE PRECISION
) TO authenticated;
