name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore Tests/GeoApp.Tests/GeoApp.Tests.csproj

    - name: Build tests
      run: dotnet build Tests/GeoApp.Tests/GeoApp.Tests.csproj --no-restore

    - name: Run tests
      run: dotnet test Tests/GeoApp.Tests/GeoApp.Tests.csproj --no-build --verbosity minimal

  unity-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          unityVersion: 6000.0.50f1
          targetPlatform: StandaloneLinux64
