---
name: .NET

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Tests/GeoApp.Tests/GeoApp.Tests.csproj

      - name: Build tests
        run: dotnet build Tests/GeoApp.Tests/GeoApp.Tests.csproj --no-restore

      - name: Run tests
        run: |
          dotnet test Tests/GeoApp.Tests/GeoApp.Tests.csproj \
            --no-build --verbosity minimal

  unity-build:
    needs: test
    runs-on: ubuntu-latest
    environment: 'Unity Secrets'
    steps:
      - name: Verify Unity secrets
        env:
          EMAIL: ${{ secrets.UNITY_EMAIL }}
          PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          LICENSE: ${{ secrets.UNITY_LICENSE }}
          SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: |
          missing=0
          if [ -n "$EMAIL" ]; then
            echo "UNITY_EMAIL provided"
          else
            echo "UNITY_EMAIL missing"
            missing=1
          fi
          if [ -n "$PASSWORD" ]; then
            echo "UNITY_PASSWORD provided"
          else
            echo "UNITY_PASSWORD missing"
            missing=1
          fi
          if [ -n "$LICENSE" ]; then
            echo "UNITY_LICENSE provided"
          else
            echo "UNITY_LICENSE missing"
          fi
          if [ -n "$SERIAL" ]; then
            echo "UNITY_SERIAL provided"
          else
            echo "UNITY_SERIAL missing"
          fi
          if [ $missing -eq 1 ]; then
            echo 'UNITY_EMAIL and UNITY_PASSWORD secrets are required' >&2
            exit 1
          fi
          if [ -z "$LICENSE" ] && [ -z "$SERIAL" ]; then
            echo 'Provide UNITY_LICENSE or UNITY_SERIAL for activation' >&2
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Activate Unity
        id: activate
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2023.1.0f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ steps.activate.outputs.unityLicense }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: .
          unityVersion: 2023.1.0f1
          targetPlatform: StandaloneLinux64
